# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ci:
    uses: Mikael-RnD/.github/workflows/uipath-ci-e2e.yml@main
    with:
      environment: prod
      orchestratorUrl: ${{ vars.ORCHESTRATOR_URL }}
      orchestratorFolder: ${{ vars.ORCHESTRATOR_FOLDER }}
      orchestratorTenant: ${{ vars.ORCHESTRATOR_TENANT }}
      organizationId: ${{ vars.ORGANIZATION_ID }}
      orchestratorApplicationScope: ${{ vars.ORCHESTRATOR_APPLICATION_SCOPE }}
    secrets:
      orchestratorApplicationId: ${{ secrets.ORCHESTRATOR_APPLICATION_ID }}
      orchestratorApplicationSecret: ${{ secrets.ORCHESTRATOR_APPLICATION_SECRET }}
