# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: NuGet/setup-nuget@v1.0.5

      - name: Setup UiPath CLI
        run: 'C:\actions-runner\UiPath.CLI.1.0.7985.19721\lib\net461\uipcli.exe package pack "$GITHUB_WORKSPACE\ProjectFolder\project.json" -o "$GITHUB_WORKSPACE" --libraryOrchestratorUrl https://cloud.uipath.com/hppcntv --libraryOrchestratorTenant Mikaels_RnD --libraryOrchestratorUsername hppcntv --libraryOrchestratorPassword tuVh9N_P5V-4yCgpu1vm3Q11HU0ZC1m3o9B_p-KoHcunm --autoVersion --outputType Process' 
      
# Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
